### ISSUE TITLE
Clarification of output (planar order + distance)

### ISSUE THREAD

**Issue by hyanwong** [vlshchur/argentum-pv#1]
I think the description of the output format could do with some improvement. From Figure 1 of the preprint, it looks like for `n` sample haplotypes, the compact tree representation should contain a planar order of `n` indices  (i.e. [0]..[n-1]), and a list of  `n-1` distances, corresponding to the heights between each adjacent pair. 

But the list of distances is of size `n` not `n-1`. It looks as if the first "distance" should perhaps be discarded?

**Comment by hyanwong** [comment]
If I can ignore the first value in the list of heights, I *think* that the following python algorithm will construct a newick string of the correct form (see my request in https://github.com/vlshchur/stable/issues/2). Might you have time to check an example or two?

```
def planar_order_to_newick(order_string, height_string, branch_lengths=True):
    orders = order_string.split(",")
    heights = np.fromstring(height_string, sep=",")[1:]
    while len(heights):
        # cluster tips together, starting at the smallest height
        target_height = np.min(heights)
        runs_of_min_height = (heights == target_height)
        # make sure all runs of ones are well-bounded
        bounded = np.hstack(([0], runs_of_min_height, [0]))
        # get 1 at run starts and -1 at run ends
        diffs = np.diff(bounded)
        removed = 0
        nwk_height = ":{}".format(target_height) if branch_lengths else ""
        for start, end in zip(np.where(diffs > 0)[0], np.where(diffs < 0)[0]):
            # merge adjacent tips of the same min_height together,
            # comma-separated, within a brace (i.e. newick format)
            start -= removed
            end -= removed
            orders[end] = "({})".format(
                               ",".join([o+nwk_height for o in orders[start:(end+1)]]))
            del orders[start:end]
            removed += end-start
        heights = heights[~runs_of_min_height]
    return(orders[0] + ";")
```

For example (not printing heights for clarity)

```
> print(planar_order_to_newick(
    "0,8,5,14,3,4,6,9,7,1,11,2,10,12,13,15",
    "0,10,8,13,14,13,5,9,7,1,13,11,11,11,11,11",
    branch_lengths=False))

"(((0,(8,5)),14),(3,((4,6),(9,(7,1))),(11,2,10,12,13,15)));"
```

or for a more complex example, using the last line of the output from your `test.txt` file:

```
> print(planar_order_to_newick(
    "13,20,34,41,46,76,80,88,92,93,98,36,28,60,61,62,1,2,3,9,14,49,77,79,82,85,86,87,89,94,95,72,24,25,44,45,67,38,40,42,37,26,29,31,32,30,81,84,91,97,99,71,83,56,59,48,64,74,16,33,69,68,75,4,15,51,78,8,39,5,27,18,17,0,6,7,10,11,12,70,73,90,96,65,66,63,21,47,58,52,55,35,57,19,23,43,54,22,50,53",
    "0,3,3,3,6,6,6,6,6,6,6,6,6,6,9,9,8,10,10,10,10,9,8,8,8,8,8,8,8,8,8,8,8,9,8,9,9,8,9,9,8,9,11,10,11,8,9,9,9,9,9,8,9,8,9,6,7,7,6,7,7,3,3,1,5,5,6,3,3,5,9,9,9,9,11,10,11,11,11,9,10,9,10,9,10,9,9,10,10,7,8,7,7,5,5,5,6,3,3,3",
    branch_lengths=False))

"(((((13,20,34,41),46,76,80,88,92,93,98,36,28,60),61,(62,1)),2,3,9,(14,(49,77,79,82,85,86,87,89,94,95,72,24),(25,44),45,(67,38),40,(42,37),26)),(29,31),((32,30),81,84,91,97,(99,71),(83,56),((59,48),64,(74,16),33,(((69,68,(75,4)),15,51),((78,8,39),5))),27,18,17,0),(6,7),10,11,((12,70),(73,90),(96,65),(66,63,21),47,((58,52),(55,35,((57,19,23,43),(54,22,50,53))))));"
```

**Comment by vlshchur** [comment]
Oh, I see now that there is a confusion. The output vector is the similarity instead of distance (as described in the manuscript). Similarity can be considered as the inverse of the distance e.g. by taking (1/similarity) or taking max(array of similarity)+1-similarity.

You are right, the first value in the similarity array can be discarded.

The small tree
"0,8,5,14,3,4,6,9,7,1,11,2,10,12,13,15",
"0,10,8,13,14,13,5,9,7,1,13,11,11,11,11,11"
should be
(((0,8),(5,(14,3),4)),((6,9),7),((1,11),2,10,12,13,15))
For example, the similarity 10 between leaves 0 and 8 is larger than similarity 8 between leaves 8 and 5. You can convert similarity to disctance by either taking the inverse of similarity (1/similarity) or taking max(array of similarity)+1-similarity. It might be more intiuitive to work with distances. In the planar ordering the tree branch is a part of array [i, j] such that s[i-1]<s[k] and s[j+1]<s[k] for any k in [i,j].

Also the implementation https://github.com/nvalimak/argentum can output Newick trees for you with the following command (similarly to scrm output)
`./main --scrm --input scrm_small.out --no-prediction --verbose --newick --nrow 5000 -L 2500000 | head -n10 | less`

**Comment by vlshchur** [comment]
I added an optional -d argument so that instead of similarity the output is distance (1+max(similarity array)-similarity). I removed the first value too, so now the length of the similarity/distance vector is n-1.

**Comment by hyanwong** [comment]
Thanks. How do I call it with the `-d` option?

```
yan$ ./argentum/argentum -d <(tail -n +7 ./argentum/test.txt) 100
Reading from -d. File contains 0 samples.
```

**Comment by vlshchur** [comment]
./argentum <(tail -n +7 test.txt) 100 -d

**Comment by hyanwong** [comment]
Ah, sorry - I tried that but was expecting 1/similarity (i.e. floating point), so thought it had made no difference. My bad. Thanks
